import turtle
t=turtle.Turtle()
# t.color("red")
turtle.setup(700, 700)
t.penup()
# t.right(90)
# t.forward(300)
# t.left(90)
# t.pendown()
# t.begin_fill()
# t.circle(300)
# t.end_fill()
# t.penup()
# t.left(90)
# t.forward(50)
# t.right(90)
# t.color("white")
# t.begin_fill()
# t.circle(250)
# t.end_fill()
# t.left(90)
# t.forward(50)
# t.right(90)
# t.color("red")
# t.begin_fill()
# t.circle(200)
# t.end_fill()
# t.circle(150)
# t.end_fill()
# t.penup()
# t.left(90)
# t.left(90)
# t.forward(50)
# t.right(90)
# t.color("blue")
# t.begin_fill()
# t.goto(0,0)
# t.forward(75)
# t.left(90)
# t.forward(25)
# t.pendown()
# t.color("white")
# t.begin_fill()
# t.setheading(-120)
# for i in range(5):
# 	t.right(40)
# 	t.forward(65)
# 	t.left(110)
# 	t.forward(65)
t.penup()
t.color("orange","yellow")
t.goto(0,-200)
t.pendown()
t.begin_fill()
t.circle(250)
t.end_fill()
t.penup()
t.goto(0,-150)
t.pencolor("brown")
t.pendown()
t.circle(180,50)
t.penup()
t.goto(0,-150)
t.left(120)
t.pendown()
t.circle(-180,50)
t.penup()
t.goto(-100,95)
t.color("brown","white")
t.pendown()
t.begin_fill()
t.circle(50)
t.end_fill()
t.dot(30,"black")
t.penup()
t.goto(100,95)
t.color("brown","white")
t.pendown()
t.begin_fill()
t.circle(50)
t.end_fill()
t.penup()
t.forward(10)
t.dot(30,"black")
t.goto(-30,-300)
t.write("好滑稽！", align="center", font=("Arial", 20, "normal"))
t.forward(100000000)



